#!/usr/bin/env python3
"""Generate the Homebrew formula for the zerobrew tap from release assets.

The tap lives in a separate repository (HernandoR/homebrew-zerobrew) because
`brew tap <user>/<repo>` resolves only to `github.com/<user>/homebrew-<repo>`.
Keeping the two in sync by hand is what left the upstream tap stranded five
releases behind (issues #16 and #17), so the release workflow calls this to
regenerate the formula instead.

Reads a `sha256sum`-format checksum file and writes a formula that pins every
asset by digest.

On Linux the statically linked musl build is preferred when it is present: it
has no glibc floor, so one binary works everywhere (issue #10). If a musl asset
is missing -- an older release, or a failed cross build -- the glibc asset is
used instead rather than emitting a URL that would 404.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

DOWNLOAD_URL = "https://github.com/HernandoR/zerobrew/releases/download"

# (formula block, nested block, asset infix). Order matters only for output.
PLATFORMS = [
    ("on_macos", "on_arm", "darwin-arm64"),
    ("on_macos", "on_intel", "darwin-x64"),
    ("on_linux", "on_arm", "linux-arm64"),
    ("on_linux", "on_intel", "linux-x64"),
]


def parse_checksums(text: str) -> dict[str, str]:
    """Parse `sha256sum` output into {filename: digest}."""
    sums: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        digest, _, name = line.partition(" ")
        name = name.lstrip("*").strip()
        if not name or len(digest) != 64:
            raise ValueError(f"malformed checksum line: {line!r}")
        sums[name] = digest
    if not sums:
        raise ValueError("checksum file contained no entries")
    return sums


def select_asset(sums: dict[str, str], binary: str, infix: str) -> tuple[str, str]:
    """Pick the asset for one platform, preferring musl on Linux.

    Returns (asset_name, sha256). Raises KeyError when neither variant exists,
    because a formula that points at a missing asset is worse than a failed
    release job.
    """
    candidates = [f"{binary}-{infix}"]
    if infix.startswith("linux-"):
        candidates.insert(0, f"{binary}-{infix}-musl")

    for name in candidates:
        if name in sums:
            return name, sums[name]

    raise KeyError(f"no asset for {binary} {infix}; tried {', '.join(candidates)}")


def render(version: str, sums: dict[str, str]) -> str:
    lines = [
        "# This file is generated by .github/scripts/generate_formula.py in",
        "# HernandoR/zerobrew and overwritten on every release. Edit it there.",
        "class Zerobrew < Formula",
        '  desc "Package manager alternative to Homebrew, in Rust"',
        '  homepage "https://github.com/HernandoR/zerobrew"',
        f'  version "{version}"',
        '  license all_of: ["Apache-2.0", "MIT"]',
        "",
        "  # Linux uses the statically linked musl build, so there is no glibc",
        "  # floor and the same binary runs in minimal containers and Colab.",
    ]

    current_outer = None
    for outer, inner, infix in PLATFORMS:
        try:
            zb_name, zb_sha = select_asset(sums, "zb", infix)
            zbx_name, zbx_sha = select_asset(sums, "zbx", infix)
        except KeyError as exc:
            raise SystemExit(f"error: {exc}") from exc

        if outer != current_outer:
            if current_outer is not None:
                lines.append("  end")
            lines.append("")
            lines.append(f"  {outer} do")
            current_outer = outer

        lines += [
            f"    {inner} do",
            f'      url "{DOWNLOAD_URL}/v{version}/{zb_name}"',
            f'      sha256 "{zb_sha}"',
            "",
            '      resource "zbx" do',
            f'        url "{DOWNLOAD_URL}/v{version}/{zbx_name}"',
            f'        sha256 "{zbx_sha}"',
            "      end",
            "    end",
        ]

    lines.append("  end")
    lines += [
        "",
        "  def install",
        "    # Matched by glob rather than rebuilt from OS/arch, so that the",
        "    # musl and glibc asset names are both handled without branching.",
        '    zb = Dir["zb-*"].first',
        '    odie "no zb binary in the download" if zb.nil?',
        '    bin.install zb => "zb"',
        "",
        "    # zbx locates zb as a sibling of its own executable, so both have to",
        "    # land in the same bin directory.",
        '    resource("zbx").stage do',
        '      zbx = Dir["zbx-*"].first',
        '      odie "no zbx binary in the download" if zbx.nil?',
        '      bin.install zbx => "zbx"',
        "    end",
        "  end",
        "",
        "  test do",
        '    assert_match version.to_s, shell_output("#{bin}/zb --version")',
        '    assert_match "zbx <formula>", shell_output("#{bin}/zbx 2>&1", 1)',
        "  end",
        "end",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="release version, without a leading v")
    parser.add_argument("--checksums", required=True, type=Path, help="SHA256SUMS file")
    parser.add_argument("--output", type=Path, help="write here instead of stdout")
    args = parser.parse_args()

    version = args.version.lstrip("v")
    sums = parse_checksums(args.checksums.read_text())
    formula = render(version, sums)

    if args.output:
        args.output.write_text(formula)
    else:
        sys.stdout.write(formula)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
